//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OverParse.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OverParse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   OverParse doesn&apos;t have write access to its folder, and won&apos;t be able to save logs or update skill mappings. This usually happens when you run it from Program Files.
        ///
        ///This is a Windows restriction, and unfortunately I can&apos;t do anything about it.\n\nPlease run OverParse as administrator, or move it somewhere else. Sorry for the inconvenience! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0001 {
            get {
                return ResourceManager.GetString("E0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oops. This is embarassing.
        ///
        ///OverParse encountered an unexpected error. If this happens again, please complain to TyroneSama at your earliest convenience. Include your log from OverParse\\logs and the following message:
        ///
        ///{0}
        ///
        ///Sorry for the inconvenience! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0002 {
            get {
                return ResourceManager.GetString("E0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OverParse failed to initialize hotkeys. This is usually because something else is already using them.
        ///
        ///The program will still work, but hotkeys will not function. Sorry for the inconvenience! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0003 {
            get {
                return ResourceManager.GetString("E0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OverParse failed to update its skill mappings. This usually means your connection hiccuped for a moment.
        ///
        ///A local copy will be used instead. If you&apos;d like to try and update again, just relaunch OverParse. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0004 {
            get {
                return ResourceManager.GetString("E0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OverParse failed to update its skill mappings. This usually means your connection hiccuped for a moment.
        ///
        ///Since you have no skill mappings downloaded, all attacks will be marked as &quot;Unknown&quot;. If you&apos;d like to try and update again, please relaunch OverParse. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0005 {
            get {
                return ResourceManager.GetString("E0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can install the parsing plugin from the PSO2 Tweaker&apos;s orb menu, under &quot;Plugins&quot;.
        ///
        ///If you don&apos;t use the PSO2 tweaker, use &quot;Help &gt; Reset OverParse...&quot; to go through setup again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0006 {
            get {
                return ResourceManager.GetString("E0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0007 {
            get {
                return ResourceManager.GetString("E0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Couldn&apos;t parse your input. Enter only a number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0008 {
            get {
                return ResourceManager.GetString("E0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There&apos;s a new version of OverParse available!
        ///
        ///You&apos;re running version {0}. The latest version is version {1}.
        ///
        ///Would you like to download it now from GitHub? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0001 {
            get {
                return ResourceManager.GetString("I0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you SURE you want to reset OverParse?
        ///
        ///This will clear all of your application settings and allow you to reselect your pso2_bin folder, but won&apos;t delete your stored logs. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0002 {
            get {
                return ResourceManager.GetString("I0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This will make the OverParse window invisible whenever PSO2 or OverParse are not in the foreground.
        ///
        ///To show the window, Alt+Tab into OverParse, or click the icon on your taskbar. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0003 {
            get {
                return ResourceManager.GetString("I0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How many seconds should the system wait before stopping an encounter? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0004 {
            get {
                return ResourceManager.GetString("I0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This doesn&apos;t actually do anything yet. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0005 {
            get {
                return ResourceManager.GetString("I0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OverParse v{0}
        ///A lightweight self-auditing tool.
        ///
        ///Shoutouts to WaifuDfnseForce.
        ///Additional shoutouts to Variant, AIDA, and everyone else who makes the Tweaker plugin possible.
        ///
        ///Please use damage information responsibly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0006 {
            get {
                return ResourceManager.GetString("I0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   That doesn&apos;t appear to be a valid pso2_bin directory.
        ///
        ///If you installed the game using default settings, it will probably be in C:\PHANTASYSTARONLINE2\pso2_bin\. Otherwise, find the location you installed to. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0007 {
            get {
                return ResourceManager.GetString("I0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select your pso2_bin directory. OverParse uses this to read your damage logs.
        ///
        ///If you picked a folder while setting up the Tweaker, choose that. Otherwise, it will be in your PSO2 installation folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0008 {
            get {
                return ResourceManager.GetString("I0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OverParse is a 3rd-party tool that breaks PSO2&apos;s Terms and Conditions. SEGA has confirmed in an official announcement that accounts found using parsing tools may be banned.
        ///
        ///If account safety is your first priority, do NOT use OverParse. You use this tool entirely at your own risk.
        ///
        ///Would you like to continue with setup? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string W0001 {
            get {
                return ResourceManager.GetString("W0001", resourceCulture);
            }
        }
    }
}
